default:
	@echo venv
	@echo http
	@echo run

venv:
	@echo source /Users/paul/github/slexil2/py3105slexil/bin/activate

http:
	python -m http.server 9999 &

run:
	open http://localhost:9999/index.html


